---
vrfs:
  X:
    rd: 26
    family:
      ipv4: true
      ipv6: true
vtp:
  domain: example.com
  mode: transparent
interfaces:
  Loopback0:
    ipv4:
      addr: 192.168.255.26
      mask: 255.255.255.255
    ipv6:
      addr: 2001::26
      mask: 128
  Vlan79:
    vrf: X
    ipv4:
      addr: 165.1.79.26
      mask: 255.255.255.0
    ipv6:
      addr: 2001:165:1:79::26
      mask: 64
  Vlan89:
    vrf: X
    ipv4:
      addr: 165.1.89.26
      mask: 255.255.255.0
    ipv6:
      addr: 2001:165:1:89::26
      mask: 64
