---
r1:
  hostname: ine_r1
  groups:
    - router
r2:
  hostname: ine_r2
  groups:
    - router
r3:
  hostname: ine_r3
  groups:
    - router
r4:
  hostname: ine_r4
  groups:
    - router
r5:
  hostname: ine_r5
  groups:
    - router
r6:
  hostname: ine_r6
  groups:
    - router
r7:
  hostname: ine_r7
  groups:
    - router
r8:
  hostname: ine_r8
  groups:
    - router
r9:
  hostname: ine_r9
  groups:
    - router
r10:
  hostname: ine_r10
  groups:
    - router
r11:
  hostname: ine_r11
  groups:
    - router
r12:
  hostname: ine_r12
  groups:
    - router
r13:
  hostname: ine_r13
  groups:
    - router
r14:
  hostname: ine_r14
  groups:
    - router
sw1:
  hostname: ine_sw1
  groups:
    - switch
sw2:
  hostname: ine_sw2
  groups:
    - switch
sw3:
  hostname: ine_sw3
  groups:
    - switch
sw4:
  hostname: ine_sw4
  groups:
    - switch
sw5:
  hostname: ine_sw5
  groups:
    - switch
sw6:
  hostname: ine_sw6
  groups:
    - switch
